#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DFFIMPORT                           101
#define IDD_DFFEXPORT                           103
#define IDD_NAMEOPT                             104
#define IDC_AUTOSMOOTH                          40000
#define IDC_V1SPIN                              40000
#define IDS_CLASSNAME                           40000
#define IDC_RS_NODENAME                         40001
#define IDS_LIBDESCRIPTION                      40001
#define IDC_V1                                  40002
#define IDS_DFFFILE                             40002
#define IDC_V2SPIN                              40003
#define IDS_AUTHOR                              40003
#define IDC_ANGLE                               40004
#define IDC_V3SPIN                              40004
#define IDS_SCENEIMPORT                         40004
#define IDC_SKINNING                            40005
#define IDS_COPYRIGHT                           40005
#define IDC_V2                                  40006
#define IDS_SCENEEXPORT                         40006
#define IDC_CONVAXIS                            40008
#define IDC_PRELIT                              40009
#define IDC_V3                                  40010
#define IDC_ANGLESPIN                           40012
#define IDC_LIGHTING                            40013
#define IDC_NORMALS                             40015
#define IDC_GAME                                40017
#define IDC_WORLDSPACE                          40019
#define IDC_HANIM                               40021
#define IDC_RS_EXTRACOLORS                      40022
#define IDC_EXPLNORM                            40023
#define IDC_STDMAT                              40024
#define IDC_TRISTRIP                            40025
#define IDC_FIXKAM                              40026
#define IDC_USERDATA                            40027
#define IDC_OBJNAMES                            40028
#define IDC_NAMES_MORE                          40029
#define IDC_NAME_ENTRY                          40029
#define IDC_NAME_GEO                            40030
#define IDC_NAME_FRM                            40031
#define IDC_NAME_CAM                            40032
#define IDC_NAME_LGT                            40033
#define IDC_NAME_MAT                            40034
#define IDC_NAME_TEX                            40035
